version: "3.9"

networks:
  selfn8n:

x-n8n: &service-n8n
  image: docker.m.daocloud.io/n8nio/n8n:latest
  networks: ['selfn8n']
  environment:
    # Postgre数据库相关配置,主要从.env读取
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

    # 非HTTPS访问必须禁用cookie
    - N8N_SECURE_COOKIE=false

    # 是否启用诊断和个性化推荐
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    
    # 是否在启动时重新安装缺失的包
    - N8N_REINSTALL_MISSING_PACKAGES=true

    # 是否允许Code节点使用内置模块
    #- NODE_FUNCTION_ALLOW_BUILTIN=*
    # 是否允许Code节点使用外部模块
    #- NODE_FUNCTION_ALLOW_EXTERNAL=*

    # (可选)安全性加密密钥
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}

    # (重要)设置域名和回调地址
    - N8N_HOST=${N8N_HOST}
    - WEBHOOK_URL=${WEBHOOK_URL}

    # 设置中文区域和界面
    - GENERIC_TIMEZONE=Asia/Shanghai
    - TZ=Asia/Shanghai
    - N8N_DEFAULT_LOCALE=zh-CN

services:
  # Postgre数据库
  postgres:
    image: docker.m.daocloud.io/postgres:16-alpine
    networks: ['selfn8n']
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # 挂载当前目录下的postgres-data指向数据库目录
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      # 如果备份文件存在，自动导入backup目录下的凭证和工作流
      # 区分是否是文件夹还是文件模式，优先导入文件夹，如果文件夹不存在，则导入文件；如果存在则只导入文件夹中的备份
      - |
          RESTORED=false  # 初始化一个标志变量
          if [ -d /home/node/backup/credentials_folder ]; then
            n8n import:credentials --separate --input=/home/node/backup/credentials_folder
            RESTORED=true
          fi
          if [ -d /home/node/backup/workflows_folder ]; then
            n8n import:workflow --separate --input=/home/node/backup/workflows_folder
            RESTORED=true
          fi
          if [ "$RESTORED" = "false" ]; then
            if [ -f /home/node/backup/credentials ]; then
              n8n import:credentials --input=/home/node/backup/credentials
            fi
            if [ -f /home/node/backup/workflows ]; then
              n8n import:workflow --input=/home/node/backup/workflows
            fi
          fi

    volumes:
      # 挂载当前路径下的bakcup
      - ./backup:/home/node/backup/
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - ./backup:/home/node/backup

      # 挂载nodes目录，用于存放自定义节点
      - ./nodes:~/.n8n/nodes
      # 汉化界面的关键挂载
      - ./dist:/usr/local/lib/node_modules/n8n/node_modules/n8n-editor-ui/dist # 挂载汉化

    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully